# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='vagas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matricula',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='disciplinas', to='sistema.Disciplina'),
        ),
    ]
