# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20161114_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=100)),
                ('disciplinas', models.ManyToManyField(to='sistema.Disciplina')),
            ],
        ),
    ]
