# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='n_matricula',
            field=models.CharField(max_length=15),
        ),
    ]
