# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20161226_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reajuste',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da Matrícula')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Aluno')),
                ('disciplinas_a_adicionar', models.ManyToManyField(blank=True, related_name='disciplinas_a_adicionar', to='sistema.Disciplina')),
                ('disciplinas_a_retirar', models.ManyToManyField(blank=True, related_name='disciplinas_a_retirar', to='sistema.Disciplina')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
